"""empty message

Revision ID: 9de4bdee6e92
Revises: 581c65f86926
Create Date: 2019-03-22 03:08:18.006406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9de4bdee6e92'
down_revision = '581c65f86926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('additional_data', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    op.drop_column('users', 'aditional_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aditional_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('users', 'verified')
    op.drop_column('users', 'additional_data')
    # ### end Alembic commands ###
