version: "3"

services:
    api:
        build: ./likepost/
        depends_on:
            - postgres
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./likepost/:/likepost/
            - ./celery/tasks/:/likepost/tasks/
        command: >
            gunicorn -b 0.0.0.0:8000
            --access-logfile -
            --reload
            --chdir /likepost
            "app:create_app()"

    postgres:
        restart: always
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./db/data:/var/lib/postgresql/data
        env_file:
            - "./db/.env"

    bot:
        build: ./bot/
        volumes:
            - ./bot/:/bot/

    rabbitmq:
        restart: always
        image: rabbitmq
        ports:
            - "5672:5672"

    celery:
        build: ./celery/
        restart: always
        volumes:
            - ./celery/:/celery/
        depends_on:
            - rabbitmq
        command: celery -A tasks.users worker --uid celery_user --loglevel=info
